blank_issues_enabled: false
contact_links:
  - name: ðŸ¤– Ask Dosu
    url: https://app.dosu.dev/b940116a-4934-4837-8264-6b7a53b02b79/ask
    about: "Ask an AI agent any question about this project. (Requires a free https://dosu.dev/ account.)"
